version: '3.1'

services:
  node-1:
    container_name: node-1
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      args:
        BUILD_PATH: cmd/cli
    ports:
      - 3000:3000
    restart: always
    environment:
      LOG_LEVEL: -4 # Debug
    networks:
      - canopy
    command: ["start"]

networks:
  canopy:
    driver: bridge
