version: '3.1'

services:
  node-1:
    container_name: node-1
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      args:
        BUILD_PATH: cmd/cli
    ports:
      - 50000:50000 # Wallet
      - 50001:50001 # Explorer
      - 50002:50002 # RPC
    networks:
      - canopy
    command: [ "start" ]
    volumes:
      - ./volumes/node_1:/root/.canopy
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"

  node-2:
    container_name: node-2
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      args:
        BUILD_PATH: cmd/cli
    ports:
      - 40000:50000 # Wallet
      - 40001:50001 # Explorer
      - 40002:50002 # RPC
    networks:
      - canopy
    command: [ "start" ]
    volumes:
      - ./volumes/node_2:/root/.canopy
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
networks:
  canopy:
    driver: bridge
